package names

var REQUEST_COOKIES = "REQUEST_COOKIES"
var REQUEST_COOKIES_NAMES = "REQUEST_COOKIES_NAMES"
var REQUEST_HEADERS = "REQUEST_HEADERS"
var REQUEST_HEADERS_NAMES = "REQUEST_HEADERS_NAMES"
var REQUEST_BODY_TYPE = "REQUEST_BODY_TYPE"
var REQUEST_URI = "REQUEST_URI"
var REQUEST_PROTOCOL = "REQUEST_PROTOCOL"
var REQUEST_URI_RAW = "REQUEST_URI_RAW"
var QUERY_STRING = "QUERY_STRING"
var REQUEST_BASENAME = "REQUEST_BASENAME"

//TODO Multipart parsing can be more detailed
var MULTIPART_BOUNDARY = "MULTIPART_BOUNDARY"
var MULTIPART_ERROR = "MULTIPART_ERROR"
